tag @s remove AbominationFlowManipulationLowCharge
tag @s remove AbominationFlowManipulationMediumCharge
tag @s remove AbominationFlowManipulationHighCharge
tag @s remove AbominationFlowManipulationMaxCharge